    export const GET_DOCTORS_REQUEST = "GET_DOCTORS_REQUEST"
    export const GET_DOCTORS_SUCCESS = "GET_DOCTORS_SUCCESS"
    export const GET_DOCTORS_FAILURE = "GET_DOCTORS_FAILURE"
    export const GET_DOCTORS_ERROR_HANDLE = "GET_DOCTORS_ERROR_HANDLE"